import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  background: {
    flex: 1,
    width,
    height,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  title: {
    fontSize: 42,
    color: '#e2d4a0',
    fontWeight: 'bold',
    marginBottom: 60,
    textShadowColor: '#000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
    fontFamily: 'serif',
    textAlign: 'center',
  },
  statsContainer: {
    marginBottom: 50,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2d4a0',
  },
  statsText: {
    fontSize: 28,
    color: '#ffffff',
    marginBottom: 20,
    fontFamily: 'serif',
    textAlign: 'center',
  },
  salvos: {
    color: '#00FF7F',
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,255,127,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  sacrificados: {
    color: '#FF4500',
    fontWeight: 'bold',
    textShadowColor: 'rgba(255,69,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  phrase: {
    fontSize: 22,
    color: '#ccc',
    textAlign: 'center',
    fontStyle: 'italic',
    marginBottom: 50,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
    fontFamily: 'serif',
    paddingHorizontal: 20,
  },
  buttonContainer: {
    alignItems: 'center',
    gap: 15,
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  button: {
    backgroundColor: '#4a0000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#e2d4a0',
    width: '100%',
    maxWidth: 280,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonReiniciar: {
    backgroundColor: '#1a472a',
  },
  buttonText: {
    color: '#e2d4a0',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'serif',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});